// client/src/components/AppSidebar.vue
<script setup lang="ts">
import { computed } from 'vue'
import { useRouter, useRoute } from 'vue-router'
import { useAuthStore } from '@/stores/auth'
import { 
  LayoutDashboard, 
  User, 
  GraduationCap, 
  Briefcase, 
  Wrench, 
  Search, 
  FileText,
  Users,
  Settings,
  LogOut,
  Menu
} from 'lucide-vue-next'

const authStore = useAuthStore()
const router = useRouter()
const route = useRoute()

const candidateLinks = [
  { path: '/candidate', label: 'Dashboard', icon: LayoutDashboard },
  { path: '/candidate/personal-data', label: 'Personal Data', icon: User },
  { path: '/candidate/education', label: 'Education', icon: GraduationCap },
  { path: '/candidate/experience', label: 'Experience', icon: Briefcase },
  { path: '/candidate/skills', label: 'Skills & Training', icon: Wrench },
  { path: '/candidate/search-jobs', label: 'Search Jobs', icon: Search },
  { path: '/candidate/my-applications', label: 'My Applications', icon: FileText },
]

const adminLinks = [
  { path: '/admin', label: 'Dashboard', icon: LayoutDashboard },
  { path: '/admin/candidates', label: 'Candidates', icon: Users },
  { path: '/admin/settings', label: 'Settings', icon: Settings },
]

const managerLinks = [
  { path: '/manager', label: 'Dashboard', icon: LayoutDashboard },
  { path: '/manager/candidates', label: 'Candidates', icon: Users },
]

const links = computed(() => {
  if (!authStore.user) return []
  switch (authStore.user.role) {
    case 'candidate': return candidateLinks
    case 'admin': return adminLinks
    case 'manager': return managerLinks
    default: return []
  }
})

const handleLogout = () => {
  authStore.logout()
  router.push('/login')
}

const isActive = (path: string) => {
  return route.path === path || route.path.startsWith(path + '/')
}
</script>

<template>
  <aside class="w-64 border-r bg-background h-screen flex flex-col">
    <div class="p-4 border-b">
      <h1 class="text-xl font-bold text-primary">SmartHire</h1>
    </div>
    
    <nav class="flex-1 p-4 space-y-1">
      <router-link
        v-for="link in links"
        :key="link.path"
        :to="link.path"
        :class="[
          'flex items-center gap-3 px-3 py-2 rounded-md text-sm transition-colors',
          isActive(link.path) 
            ? 'bg-primary text-primary-foreground' 
            : 'text-muted-foreground hover:bg-muted hover:text-foreground'
        ]"
      >
        <component :is="link.icon" class="h-4 w-4" />
        {{ link.label }}
      </router-link>
    </nav>
    
    <div class="p-4 border-t">
      <div class="flex items-center gap-3 mb-4">
        <div class="w-8 h-8 rounded-full bg-primary/10 flex items-center justify-center">
          <User class="h-4 w-4 text-primary" />
        </div>
        <div class="flex-1 min-w-0">
          <p class="text-sm font-medium truncate">{{ authStore.user?.fullName }}</p>
          <p class="text-xs text-muted-foreground capitalize">{{ authStore.user?.role }}</p>
        </div>
      </div>
      <button
        @click="handleLogout"
        class="flex items-center gap-2 w-full px-3 py-2 text-sm text-muted-foreground hover:bg-muted hover:text-foreground rounded-md transition-colors"
      >
        <LogOut class="h-4 w-4" />
        Logout
      </button>
    </div>
  </aside>
</template>

// client/src/components/app-sidebar.tsx
import { Link, useLocation } from "wouter";
import { useAuth } from "@/lib/authContext";
import {
  Sidebar,
  SidebarContent,
  SidebarGroup,
  SidebarGroupLabel,
  SidebarGroupContent,
  SidebarMenu,
  SidebarMenuItem,
  SidebarMenuButton,
  SidebarHeader,
  SidebarFooter
} from "@/components/ui/sidebar";
import { Button } from "@/components/ui/button";
import { Avatar, AvatarFallback } from "@/components/ui/avatar";
import { Badge } from "@/components/ui/badge";
import {
  LayoutDashboard,
  User,
  GraduationCap,
  Briefcase,
  Award,
  Search,
  FileText,
  Users,
  Settings,
  LogOut
} from "lucide-react";

// Menu items for different roles
const candidateMenu = [
  { title: "Dashboard", url: "/candidate", icon: LayoutDashboard },
  { title: "Personal Data", url: "/candidate/personal-data", icon: User },
  { title: "Education", url: "/candidate/education", icon: GraduationCap },
  { title: "Experience", url: "/candidate/experience", icon: Briefcase },
  { title: "Skills & Training", url: "/candidate/skills", icon: Award },
  { title: "Search Jobs", url: "/candidate/search-jobs", icon: Search },
  { title: "My Applications", url: "/candidate/my-applications", icon: FileText }
];

const adminMenu = [
  { title: "Dashboard", url: "/admin", icon: LayoutDashboard },
  { title: "Candidates", url: "/admin/candidates", icon: Users },
  { title: "Settings", url: "/admin/settings/users", icon: Settings }
];

const managerMenu = [
  { title: "Dashboard", url: "/manager", icon: LayoutDashboard },
  { title: "Candidates", url: "/manager/candidates", icon: Users }
];

export function AppSidebar() {
  const [location] = useLocation();
  const { user, logout } = useAuth();

  if (!user) return null;

  const getMenuItems = () => {
    switch (user.role) {
      case "candidate":
        return candidateMenu;
      case "admin":
        return adminMenu;
      case "manager":
        return managerMenu;
      default:
        return [];
    }
  };

  const menuItems = getMenuItems();

  const getRoleBadgeColor = () => {
    switch (user.role) {
      case "candidate":
        return "bg-blue-100 text-blue-700 dark:bg-blue-900 dark:text-blue-300";
      case "admin":
        return "bg-purple-100 text-purple-700 dark:bg-purple-900 dark:text-purple-300";
      case "manager":
        return "bg-green-100 text-green-700 dark:bg-green-900 dark:text-green-300";
      default:
        return "";
    }
  };

  const getInitials = (name: string) => {
    return name
      .split(" ")
      .map((n) => n[0])
      .join("")
      .toUpperCase()
      .slice(0, 2);
  };

  return (
    <Sidebar>
      <SidebarHeader className="border-b p-4">
        <div className="flex items-center gap-3">
          <div className="w-10 h-10 rounded-lg bg-primary flex items-center justify-center">
            <Briefcase className="w-5 h-5 text-primary-foreground" />
          </div>
          <div>
            <h1 className="font-bold text-lg">SmartHire</h1>
            <Badge className={`text-xs ${getRoleBadgeColor()}`} data-testid="badge-role">
              {user.role.charAt(0).toUpperCase() + user.role.slice(1)}
            </Badge>
          </div>
        </div>
      </SidebarHeader>

      <SidebarContent>
        <SidebarGroup>
          <SidebarGroupLabel>Navigation</SidebarGroupLabel>
          <SidebarGroupContent>
            <SidebarMenu>
              {menuItems.map((item) => {
                const isActive = location === item.url || 
                  (item.url !== "/" && location.startsWith(item.url));
                
                return (
                  <SidebarMenuItem key={item.title}>
                    <SidebarMenuButton 
                      asChild 
                      isActive={isActive}
                      data-testid={`nav-${item.title.toLowerCase().replace(/\s+/g, "-")}`}
                    >
                      <Link href={item.url}>
                        <item.icon className="w-4 h-4" />
                        <span>{item.title}</span>
                      </Link>
                    </SidebarMenuButton>
                  </SidebarMenuItem>
                );
              })}
            </SidebarMenu>
          </SidebarGroupContent>
        </SidebarGroup>
      </SidebarContent>

      <SidebarFooter className="border-t p-4">
        <div className="flex items-center gap-3 mb-3">
          <Avatar className="h-9 w-9">
            <AvatarFallback className="bg-primary/10 text-primary text-sm">
              {getInitials(user.fullName)}
            </AvatarFallback>
          </Avatar>
          <div className="flex-1 min-w-0">
            <p className="text-sm font-medium truncate" data-testid="text-username">
              {user.fullName}
            </p>
            <p className="text-xs text-muted-foreground truncate">
              {user.email}
            </p>
          </div>
        </div>
        <Button 
          variant="outline" 
          className="w-full justify-start gap-2" 
          onClick={logout}
          data-testid="button-logout"
        >
          <LogOut className="w-4 h-4" />
          Sign Out
        </Button>
      </SidebarFooter>
    </Sidebar>
  );
}
